export const ADDRESS_GET_REQUEST = 'ADDRESS_GET_REQUEST';
export const ADDRESS_GET_SUCCESS = 'ADDRESS_GET_SUCCESS';
export const ADDRESS_GET_FAIL = 'ADDRESS_GET_FAIL';

export const ADDRESS_CREATE_REQUEST = 'ADDRESS_CREATE_REQUEST';
export const ADDRESS_CREATE_SUCCESS = 'ADDRESS_CREATE_SUCCESS';
export const ADDRESS_CREATE_FAIL = 'ADDRESS_CREATE_FAIL';
export const ADDRESS_CREATE_RESET = 'ADDRESS_CREATE_RESET';