// Wishlist
export const GET_WISHLIST_REQUEST = 'GET_WISHLIST_REQUEST'
export const GET_WISHLIST_SUCCESS = 'GET_WISHLIST_SUCCESS'
export const GET_WISHLIST_FAIL = 'GET_WISHLIST_FAIL'

export const ADD_TO_WISHLIST_REQUEST = 'ADD_TO_WISHLIST_REQUEST'
export const ADD_TO_WISHLIST_SUCCESS = 'ADD_TO_WISHLIST_SUCCESS'    
export const ADD_TO_WISHLIST_FAIL = 'ADD_TO_WISHLIST_FAIL'

export const REMOVE_FROM_WISHLIST_REQUEST = 'REMOVE_FROM_WISHLIST_REQUEST'
export const REMOVE_FROM_WISHLIST_SUCCESS = 'REMOVE_FROM_WISHLIST_SUCCESS'
export const REMOVE_FROM_WISHLIST_FAIL = 'REMOVE_FROM_WISHLIST_FAIL'

// Save for later
export const GET_SAVE_FOR_LATER_REQUEST = 'GET_SAVE_FOR_LATER_REQUEST'
export const GET_SAVE_FOR_LATER_SUCCESS = 'GET_SAVE_FOR_LATER_SUCCESS'
export const GET_SAVE_FOR_LATER_FAIL = 'GET_SAVE_FOR_LATER_FAIL'

export const ADD_TO_SAVE_FOR_LATER_REQUEST = 'ADD_TO_SAVE_FOR_LATER_REQUEST'
export const ADD_TO_SAVE_FOR_LATER_SUCCESS = 'ADD_TO_SAVE_FOR_LATER_SUCCESS'
export const ADD_TO_SAVE_FOR_LATER_FAIL = 'ADD_TO_SAVE_FOR_LATER_FAIL'

export const REMOVE_FROM_SAVE_FOR_LATER_REQUEST = 'REMOVE_FROM_SAVE_FOR_LATER_REQUEST'
export const REMOVE_FROM_SAVE_FOR_LATER_SUCCESS = 'REMOVE_FROM_SAVE_FOR_LATER_SUCCESS'
export const REMOVE_FROM_SAVE_FOR_LATER_FAIL = 'REMOVE_FROM_SAVE_FOR_LATER_FAIL'
