export const ORDER_PRE_CREATE_REQUEST = 'ORDER_PRE_CREATE_REQUEST'
export const ORDER_PRE_CREATE_SUCCESS = 'ORDER_PRE_CREATE_SUCCESS'
export const ORDER_PRE_CREATE_FAIL = 'ORDER_PRE_CREATE_FAIL'

export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST'
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL'
export const ORDER_CREATE_RESET = 'ORDER_CREATE_RESET'
export const ORDER_CREATE_PAYMENT_MP = 'ORDER_CREATE_PAYMENT_MP'

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST'
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS'
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL'

export const ORDER_DETAILS_UNLOGGED_REQUEST = 'ORDER_DETAILS_UNLOGGED_REQUEST'
export const ORDER_DETAILS_UNLOGGED_SUCCESS = 'ORDER_DETAILS_UNLOGGED_SUCCESS'
export const ORDER_DETAILS_UNLOGGED_FAIL = 'ORDER_DETAILS_UNLOGGED_FAIL'

export const ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST'
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS'
export const ORDER_PAY_FAIL = 'ORDER_PAY_FAIL'

export const ORDER_UPLOAD_PROOF_UNLOGGED_REQUEST = 'ORDER_UPLOAD_PROOF_UNLOGGED_REQUEST'
export const ORDER_UPLOAD_PROOF_UNLOGGED_SUCCESS = 'ORDER_UPLOAD_PROOF_UNLOGGED_SUCCESS'
export const ORDER_UPLOAD_PROOF_UNLOGGED_FAIL = 'ORDER_UPLOAD_PROOF_UNLOGGED_FAIL'

export const ORDERS_LIST_REQUEST = 'ORDERS_LIST_REQUEST'
export const ORDERS_LIST_SUCCESS = 'ORDERS_LIST_SUCCESS'
export const ORDERS_LIST_FAIL = 'ORDERS_LIST_FAIL'
export const ORDERS_LIST_RESET = 'ORDERS_LIST_RESET'

export const ORDERS_ALL_LIST_REQUEST = 'ORDERS_ALL_LIST_REQUEST'
export const ORDERS_ALL_LIST_SUCCESS = 'ORDERS_ALL_LIST_SUCCESS'
export const ORDERS_ALL_LIST_FAIL = 'ORDERS_ALL_LIST_FAIL'

export const ORDER_UPDATE_PAID_REQUEST = 'ORDER_UPDATE_PAID_REQUEST'
export const ORDER_UPDATE_PAID_SUCCESS = 'ORDER_UPDATE_PAID_SUCCESS'
export const ORDER_UPDATE_PAID_FAIL = 'ORDER_UPDATE_PAID_FAIL'

export const ORDER_UPDATE_DELIVERED_REQUEST = 'ORDER_UPDATE_DELIVERED_REQUEST'
export const ORDER_UPDATE_DELIVERED_SUCCESS = 'ORDER_UPDATE_DELIVERED_SUCCESS'
export const ORDER_UPDATE_DELIVERED_FAIL = 'ORDER_UPDATE_DELIVERED_FAIL'

export const ORDER_ADD_TRACKING_NUMBER_REQUEST = 'ORDER_ADD_TRACKING_NUMBER_REQUEST'
export const ORDER_ADD_TRACKING_NUMBER_SUCCESS = 'ORDER_ADD_TRACKING_NUMBER_SUCCESS'
export const ORDER_ADD_TRACKING_NUMBER_FAIL = 'ORDER_ADD_TRACKING_NUMBER_FAIL'

export const ORDER_ADD_TRACKING_URL_REQUEST = 'ORDER_ADD_TRACKING_URL_REQUEST'
export const ORDER_ADD_TRACKING_URL_SUCCESS = 'ORDER_ADD_TRACKING_URL_SUCCESS'
export const ORDER_ADD_TRACKING_URL_FAIL = 'ORDER_ADD_TRACKING_URL_FAIL'

export const ORDER_DELETE_TRACKING_NUMBER_REQUEST = 'ORDER_DELETE_TRACKING_NUMBER_REQUEST'
export const ORDER_DELETE_TRACKING_NUMBER_SUCCESS = 'ORDER_DELETE_TRACKING_NUMBER_SUCCESS'
export const ORDER_DELETE_TRACKING_NUMBER_FAIL = 'ORDER_DELETE_TRACKING_NUMBER_FAIL'

export const ORDER_DELETE_TRACKING_URL_REQUEST = 'ORDER_DELETE_TRACKING_URL_REQUEST'
export const ORDER_DELETE_TRACKING_URL_SUCCESS = 'ORDER_DELETE_TRACKING_URL_SUCCESS'
export const ORDER_DELETE_TRACKING_URL_FAIL = 'ORDER_DELETE_TRACKING_URL_FAIL'




// export const ORDER_USER_LIST_REQUEST = 'ORDER_USER_LIST_REQUEST'
// export const ORDER_USER_LIST_SUCCESS = 'ORDER_USER_LIST_SUCCESS'
// export const ORDER_USER_LIST_FAIL = 'ORDER_USER_LIST_FAIL'

