# Generated by Django 4.1.1 on 2022-09-18 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_order__order_number_order__order_origin_website'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='_order_number',
            new_name='_External_order_number',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='_order_origin_website',
            new_name='_External_order_origin_website',
        ),
    ]
