# Generated by Django 4.1.1 on 2022-10-06 05:12

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_order_paymentlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paymentLink',
        ),
        migrations.AddField(
            model_name='order',
            name='expiryDate',
            field=models.DateTimeField(blank=True, default=base.models.Order.expiration, null=True),
        ),
    ]
