# Generated by Django 4.1.1 on 2022-10-06 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_remove_order_paymentlink_order_expirydate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='isPaid',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Cancelled', 'Cancelled'), ('Expired', 'Expired'), ('Paid', 'Paid')], default='Pending', max_length=10),
        ),
    ]
