# Generated by Django 4.1.1 on 2022-10-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_remove_order_ispaid_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
    ]
