# Generated by Django 4.1.1 on 2022-10-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_shippingaddress_lat_alter_shippingaddress_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
    ]
