# Generated by Django 4.1.1 on 2022-10-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_order_ispaid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Cancelled', 'Cancelled'), ('Expired', 'Expired'), ('Success', 'Success')], default='Pending', max_length=10),
        ),
    ]
