# Generated by Django 4.1.1 on 2022-11-04 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='price',
        ),
    ]
