# Generated by Django 4.1.1 on 2022-11-05 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_cartitem_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
