# Generated by Django 4.1.1 on 2022-11-05 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_alter_cartitem_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='stock',
        ),
    ]
