# Generated by Django 4.1.1 on 2022-11-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_remove_cartitem_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='stock',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
