# Generated by Django 4.1.1 on 2022-11-06 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_shippingaddress_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='shippingPrice',
        ),
    ]
