# Generated by Django 4.1.1 on 2022-11-06 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_remove_shippingaddress_shippingprice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name_plural': 'Shipping Addresses'},
        ),
    ]
