# Generated by Django 4.1.1 on 2022-11-14 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
