# Generated by Django 4.1.1 on 2022-11-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0047_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_scraped',
            field=models.BooleanField(default=False),
        ),
    ]
