# Generated by Django 4.1.1 on 2022-11-19 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0048_product_is_scraped'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='original_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
