# Generated by Django 4.1.1 on 2022-11-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0049_product_original_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='original_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
