# Generated by Django 4.1.1 on 2022-12-01 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0052_remove_size_product_product_updatedat_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.product'),
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
