# Generated by Django 4.1.1 on 2022-12-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0056_remove_color_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='stock',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
