# Generated by Django 4.1.1 on 2022-12-06 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0057_size_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='stock',
        ),
    ]
