# Generated by Django 4.1.1 on 2022-12-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0059_productattribute_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='color',
            field=models.ManyToManyField(blank=True, to='base.color'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='size',
            field=models.ManyToManyField(blank=True, to='base.size'),
        ),
    ]
