# Generated by Django 4.1.1 on 2023-01-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0060_alter_productattribute_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='stock',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
