# Generated by Django 4.1.1 on 2023-01-19 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0061_remove_cartitem_stock_cartitem_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='stock',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
