# Generated by Django 4.1.1 on 2023-03-21 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0067_remove_product_brand_product_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_viewed_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
