# Generated by Django 4.1.1 on 2023-04-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0069_productview'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paymentProof',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
