# Generated by Django 4.1.1 on 2023-04-16 03:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0070_order_paymentproof'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='addedAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
