# Generated by Django 4.1.1 on 2023-04-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0071_wishlistitem_addedat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-createdAt']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['?']},
        ),
        migrations.AlterModelOptions(
            name='wishlistitem',
            options={'ordering': ['-addedAt']},
        ),
        migrations.AddField(
            model_name='order',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
