# Generated by Django 4.1.1 on 2023-04-22 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0074_stocknotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocknotification',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
