# Generated by Django 4.1.1 on 2023-04-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0076_alter_stocknotification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='trackingNumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='trackingUrl',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
