# Generated by Django 4.1.1 on 2023-05-02 13:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0077_order_trackingnumber_order_trackingurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
