# Generated by Django 4.1.1 on 2023-06-06 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0079_ticker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticker',
            old_name='ticker',
            new_name='message',
        ),
    ]
